version: "3.8"
services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: ./Dockerfile
    env_file:
      - ./api/.env
    ports:
      - 5678:5678
    networks:
      - simple-express-api
    restart: always
  db:
    container_name: db
    build:
      context: ./db
      dockerfile: ./Dockerfile
    env_file:
      - ./api/.env
    ports:
      - 5432:5432
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
    networks:
      - simple-express-api
    restart: always

networks:
  simple-express-api:
